# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# command to install dependencies
install: pip install -U tox-travis

# command to run tests
script: tox

# Jobs (with stages)
jobs:
  include:
    - stage: deploy
      script: poetry run invoke docs
      before_script:
        - pip install poetry
        - poetry install
      python: 3.8
      deploy:
        provider: pages
        local-dir: docs/_build
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        on:
           branch: master