language: python
python:
- 3.8
- 3.7
- 3.6
install: 
  - pip install -U tox-travis
  - pip install --upgrade pip
script: tox
jobs:
  include:
  - stage: deploy
    before_deploy:
    - pip install poetry
    - poetry install
    - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
    python: 3.6
    deploy:
      provider: script
      script: poetry publish --build 
      on:
        tags: true
