language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
jobs:
  include:
  - stage: deploy
    script: poetry run invoke docs
    before_script:
    - pip install poetry
    - poetry install
    python: 3.8
    deploy:
      provider: pages
      local-dir: docs/_build
      skip-cleanup: true
      github-token: "$GH_TOKEN"
      keep-history: true
      on:
        branch: master
deploy:
  password:
    secure: 14m1qlv5gq14tJ2mWOLqETSrv+Jf35BMCMMdzmwbKk9wddJEmqoxz7qha9IPxFpjyNabV9x/LphAPEMNFgr6okpe7fGrJylzAOA0zW8tKRlTFqWLNnJpePcaemLWVxO94CgALOHqKn1xdQB/zEiA12JlGwWsYq6ABQK0Bsj6N7SFcuMVGMcYD6zm7vQX7yX1KYn6Prm+c1rZeUnHYGLmliaaw+L8JxYla8zCEd29hjGWdsucAkwknOBxEV4vbN0PhtRAA+LR8bj5rmLBwsgYWgcChpKv5pNvbHZOR81bm1pPYo8IONBQGJGSerjSTR7a9mrg+Dn5Zw0q0o0PxyegmMnjsZOlFRx82usRdTP8E8lUt248UH01K6IGSN8oVJxuEWfLe3I69LuCot46lFjLjLRf6UWBiwVT9Su8LYr4nDpyvimmNRqEfd3F3IAFVPwvDydd+oEoVRh/haUjUNAuhi9vRQh6zTDptajonGv0w9Hr9ARK++C/6qkkCe/UhGe3wjybhfRle6r98maBvhe1qdAL3Ai3WZG87oQO38SqmfY2Qi96KwuYs6s55lT23vmR2S9V2b24akQ3AkpA454r3pK+30rshF9a4T4/pXfQTLvzs6DYN3j3WDbZfajdVk5yXZX5KOk57fU+QiJAdswrmXiwwJcQbd02MUu+5pkeNXE=
