# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7

# command to install dependencies
install: pip install -U tox-travis

# command to run tests
script: tox

# Jobs (with stages)
jobs:
  include:
    - stage: deploy
      script: poetry run invoke docs
      before_script:
        - pip install poetry
        - poetry install
      python: 3.8
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: rhonin
        on:
          tags: true