language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
jobs:
  include:
  - stage: deploy
    before_deploy:
    - pip install poetry
    - poetry install
    - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
    - poetry build
    python: 3.8
    deploy:
      provider: script
      script: poetry publish
      on:
        tags: true
